services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile 

    restart: always
    env_file:
      - .env 
    depends_on:
      - redis
      - mongodb
    networks:
      - rede_academico
    ports:
      - "8080:8080"
  
  redis:
    image: redis/redis-stack:latest
    container_name: redis_app
    ports:
      - "6379:6379"   # Porta do banco de dados
      - "8001:8001"   # Interface visual (RedisInsight)
    volumes:
      - redis_data:/data
    restart: always


  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - rede_academico

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  rede_academico:
    driver: bridge 

